import { createContext, useContext, useState, useCallback } from "react";

export type LangCode = "en" | "es" | "fr" | "am" | "zh" | "ko";

export const LANGUAGES: { code: LangCode; label: string; native: string }[] = [
  { code: "en", label: "English", native: "English" },
  { code: "es", label: "Spanish", native: "Español" },
  { code: "fr", label: "French", native: "Français" },
  { code: "am", label: "Amharic", native: "አማርኛ" },
  { code: "zh", label: "Chinese", native: "中文" },
  { code: "ko", label: "Korean", native: "한국어" },
];

const translations: Record<LangCode, Record<string, string>> = {
  en: {
    "hero.title.1": "Navigate D.C. resources",
    "hero.title.2": "with confidence",
    "hero.subtitle": "Connecting Washington, D.C. residents with food assistance and healthcare — powered by verified government data and AI.",
    "hero.cta": "Explore the Map",
    "hero.note": "No sign-up required · Free · Open-source",
    "features.heading": "What EquityMap offers",
    "feature.map": "Resource Map",
    "feature.map.desc": "450+ verified SNAP retailers and healthcare facilities across Washington, D.C., sourced from USDA and DC government datasets.",
    "feature.ai": "EquityGuide AI",
    "feature.ai.desc": "An AI assistant that explains benefit eligibility, the 80-hour work requirement, and helps you find resources near you.",
    "feature.screener": "Eligibility Screener",
    "feature.screener.desc": "A guided, step-by-step flow that assesses your SNAP eligibility in under 30 seconds — no account required.",
    "cta.title": "Ready to find resources?",
    "cta.subtitle": "Search by address, explore the map, or chat with EquityGuide.",
    "cta.button": "Get Started",
    "footer": "EquityMap · Built with open data · Washington, D.C.",
    "search.placeholder": "Search an address...",
    "chat.placeholder": "Ask about SNAP, Medicaid, benefits...",
    "chat.welcome": "Hi! I'm EquityGuide, your AI-powered assistant for navigating food, medical, and community resources across D.C. How can I help?",
    "chat.screener": "Check my SNAP eligibility",
    "chat.work": "What's the 80-hour rule?",
    "chat.health": "Find health resources",
    "nearby": "Nearby Resources",
    "verified": "verified resources",
    "legend.food": "Food / SNAP",
    "legend.health": "Healthcare",
    "about.title": "About EquityMap",
    "about.body": "EquityMap helps D.C. residents navigate \"Benefit Deserts\" inspired by the 2026 federal budget changes. Using AI and verified public data, EquityMap connects communities with food assistance, healthcare, and essential resources — because everyone deserves equitable access.",
    "filters": "Filters",
    "directions": "Directions",
    "details": "Details",
    "close": "Close",
    "get.directions": "Get Directions",
  },
  es: {
    "hero.title.1": "Navega los recursos de D.C.",
    "hero.title.2": "con confianza",
    "hero.subtitle": "Conectando a los residentes de Washington, D.C. con asistencia alimentaria y atención médica — con datos verificados del gobierno e IA.",
    "hero.cta": "Explorar el Mapa",
    "hero.note": "Sin registro · Gratis · Código abierto",
    "features.heading": "Lo que ofrece EquityMap",
    "feature.map": "Mapa de Recursos",
    "feature.map.desc": "Más de 450 tiendas SNAP y centros de salud verificados en Washington, D.C., de fuentes del USDA y el gobierno de DC.",
    "feature.ai": "EquityGuide IA",
    "feature.ai.desc": "Un asistente de IA que explica la elegibilidad de beneficios, el requisito de 80 horas y te ayuda a encontrar recursos cercanos.",
    "feature.screener": "Evaluador de Elegibilidad",
    "feature.screener.desc": "Un flujo guiado paso a paso que evalúa tu elegibilidad para SNAP en menos de 30 segundos — sin cuenta requerida.",
    "cta.title": "¿Listo para encontrar recursos?",
    "cta.subtitle": "Busca por dirección, explora el mapa o habla con EquityGuide.",
    "cta.button": "Comenzar",
    "footer": "EquityMap · Datos abiertos · Washington, D.C.",
    "search.placeholder": "Buscar una dirección...",
    "chat.placeholder": "Pregunta sobre SNAP, Medicaid, beneficios...",
    "chat.welcome": "¡Hola! Soy EquityGuide, tu asistente de IA para navegar recursos de alimentos, salud y comunidad en D.C. ¿En qué puedo ayudarte?",
    "chat.screener": "Verificar mi elegibilidad SNAP",
    "chat.work": "¿Qué es la regla de 80 horas?",
    "chat.health": "Encontrar recursos de salud",
    "nearby": "Recursos Cercanos",
    "verified": "recursos verificados",
    "legend.food": "Alimentos / SNAP",
    "legend.health": "Salud",
    "about.title": "Sobre EquityMap",
    "about.body": "EquityMap ayuda a los residentes de D.C. a navegar los \"Desiertos de Beneficios\" inspirados por los cambios presupuestarios de 2026. Usando IA y datos públicos verificados, conecta a las comunidades con recursos esenciales.",
    "filters": "Filtros",
    "directions": "Direcciones",
    "details": "Detalles",
    "close": "Cerrar",
    "get.directions": "Obtener Direcciones",
  },
  fr: {
    "hero.title.1": "Naviguez les ressources de D.C.",
    "hero.title.2": "en toute confiance",
    "hero.subtitle": "Connecter les résidents de Washington, D.C. avec l'aide alimentaire et les soins de santé — grâce aux données gouvernementales vérifiées et à l'IA.",
    "hero.cta": "Explorer la Carte",
    "hero.note": "Sans inscription · Gratuit · Open-source",
    "features.heading": "Ce que propose EquityMap",
    "feature.map": "Carte des Ressources",
    "feature.map.desc": "Plus de 450 détaillants SNAP et établissements de santé vérifiés à Washington, D.C., provenant de l'USDA et du gouvernement de DC.",
    "feature.ai": "EquityGuide IA",
    "feature.ai.desc": "Un assistant IA qui explique l'éligibilité aux prestations, l'exigence de 80 heures et vous aide à trouver des ressources proches.",
    "feature.screener": "Évaluateur d'Éligibilité",
    "feature.screener.desc": "Un processus guidé étape par étape qui évalue votre éligibilité SNAP en moins de 30 secondes — aucun compte requis.",
    "cta.title": "Prêt à trouver des ressources?",
    "cta.subtitle": "Recherchez par adresse, explorez la carte ou discutez avec EquityGuide.",
    "cta.button": "Commencer",
    "footer": "EquityMap · Données ouvertes · Washington, D.C.",
    "search.placeholder": "Rechercher une adresse...",
    "chat.placeholder": "Posez vos questions sur SNAP, Medicaid...",
    "chat.welcome": "Bonjour! Je suis EquityGuide, votre assistant IA pour naviguer les ressources alimentaires, médicales et communautaires à D.C. Comment puis-je vous aider?",
    "chat.screener": "Vérifier mon éligibilité SNAP",
    "chat.work": "Quelle est la règle des 80 heures?",
    "chat.health": "Trouver des ressources santé",
    "nearby": "Ressources Proches",
    "verified": "ressources vérifiées",
    "legend.food": "Alimentation / SNAP",
    "legend.health": "Santé",
    "about.title": "À propos d'EquityMap",
    "about.body": "EquityMap aide les résidents de D.C. à naviguer les \"Déserts de Prestations\" inspirés par les changements budgétaires de 2026. En utilisant l'IA et des données publiques vérifiées, il connecte les communautés aux ressources essentielles.",
    "filters": "Filtres",
    "directions": "Itinéraire",
    "details": "Détails",
    "close": "Fermer",
    "get.directions": "Obtenir l'Itinéraire",
  },
  am: {
    "hero.title.1": "የ D.C. ሀብቶችን ያስሱ",
    "hero.title.2": "በልበ ሙሉነት",
    "hero.subtitle": "የዋሽንግተን ዲሲ ነዋሪዎችን ከምግብ ድጋፍ እና ጤና አገልግሎት ጋር ማገናኘት — በተረጋገጡ የመንግስት ውሂብ እና AI።",
    "hero.cta": "ካርታውን ያስሱ",
    "hero.note": "ምዝገባ አያስፈልግም · ነፃ · ክፍት ምንጭ",
    "features.heading": "EquityMap የሚሰጠው",
    "feature.map": "የሀብት ካርታ",
    "feature.map.desc": "ከ450 በላይ የተረጋገጡ የ SNAP ቸርቻሪዎች እና የጤና ተቋማት በዋሽንግተን ዲሲ።",
    "feature.ai": "EquityGuide AI",
    "feature.ai.desc": "ስለ ጥቅማ ጥቅም ብቃት እና የ80 ሰዓት ደንብ የሚያብራራ የ AI ረዳት።",
    "feature.screener": "የብቃት ገምጋሚ",
    "feature.screener.desc": "የ SNAP ብቃትዎን በ30 ሰከንድ ውስጥ የሚገመግም ደረጃ በደረጃ ፍሰት።",
    "cta.title": "ሀብቶችን ለማግኘት ዝግጁ ነዎት?",
    "cta.subtitle": "በአድራሻ ይፈልጉ ወይም ከ EquityGuide ጋር ይነጋገሩ።",
    "cta.button": "ይጀምሩ",
    "footer": "EquityMap · ክፍት ውሂብ · ዋሽንግተን ዲሲ",
    "search.placeholder": "አድራሻ ይፈልጉ...",
    "chat.placeholder": "ስለ SNAP፣ Medicaid ይጠይቁ...",
    "chat.welcome": "ሰላም! እኔ EquityGuide ነኝ፣ በ D.C. ውስጥ ያሉ የምግብ፣ የጤና እና የማህበረሰብ ሀብቶችን ለማሰስ የ AI ረዳትዎ። እንዴት ልረዳዎ?",
    "chat.screener": "የ SNAP ብቃቴን ያረጋግጡ",
    "chat.work": "የ80 ሰዓት ደንብ ምንድነው?",
    "chat.health": "የጤና ሀብቶችን ያግኙ",
    "nearby": "በአቅራቢያ ያሉ ሀብቶች",
    "verified": "የተረጋገጡ ሀብቶች",
    "legend.food": "ምግብ / SNAP",
    "legend.health": "ጤና",
    "about.title": "ስለ EquityMap",
    "about.body": "EquityMap የ D.C. ነዋሪዎች በ2026 የበጀት ለውጦች የተፈጠሩ የጥቅም በረሃዎችን እንዲያስሱ ያግዛል።",
    "filters": "ማጣሪያዎች",
    "directions": "አቅጣጫዎች",
    "details": "ዝርዝሮች",
    "close": "ዝጋ",
    "get.directions": "አቅጣጫ ያግኙ",
  },
  zh: {
    "hero.title.1": "查找华盛顿特区资源",
    "hero.title.2": "充满信心",
    "hero.subtitle": "将华盛顿特区居民与食品援助和医疗保健联系起来——由经过验证的政府数据和AI驱动。",
    "hero.cta": "探索地图",
    "hero.note": "无需注册 · 免费 · 开源",
    "features.heading": "EquityMap 提供什么",
    "feature.map": "资源地图",
    "feature.map.desc": "华盛顿特区超过450个经过验证的SNAP零售商和医疗设施。",
    "feature.ai": "EquityGuide AI",
    "feature.ai.desc": "一个AI助手，解释福利资格、80小时工作要求，并帮助您找到附近的资源。",
    "feature.screener": "资格评估器",
    "feature.screener.desc": "一个引导式的逐步流程，在30秒内评估您的SNAP资格——无需注册。",
    "cta.title": "准备好查找资源了吗？",
    "cta.subtitle": "按地址搜索、探索地图或与EquityGuide对话。",
    "cta.button": "开始使用",
    "footer": "EquityMap · 开放数据 · 华盛顿特区",
    "search.placeholder": "搜索地址...",
    "chat.placeholder": "询问SNAP、Medicaid、福利...",
    "chat.welcome": "你好！我是EquityGuide，您的AI助手，帮助您查找特区的食品、医疗和社区资源。有什么可以帮您？",
    "chat.screener": "检查我的SNAP资格",
    "chat.work": "什么是80小时规则？",
    "chat.health": "查找健康资源",
    "nearby": "附近资源",
    "verified": "已验证资源",
    "legend.food": "食品 / SNAP",
    "legend.health": "医疗",
    "about.title": "关于 EquityMap",
    "about.body": "EquityMap帮助特区居民了解2026年联邦预算变化带来的「福利沙漠」。使用AI和经过验证的公共数据，连接社区与基本资源。",
    "filters": "筛选",
    "directions": "导航",
    "details": "详情",
    "close": "关闭",
    "get.directions": "获取路线",
  },
  ko: {
    "hero.title.1": "D.C. 자원을 탐색하세요",
    "hero.title.2": "자신감을 가지고",
    "hero.subtitle": "워싱턴 D.C. 주민들을 식품 지원 및 의료 서비스와 연결 — 검증된 정부 데이터와 AI로 구동됩니다.",
    "hero.cta": "지도 탐색",
    "hero.note": "가입 불필요 · 무료 · 오픈소스",
    "features.heading": "EquityMap이 제공하는 것",
    "feature.map": "자원 지도",
    "feature.map.desc": "워싱턴 D.C. 전역의 450개 이상의 검증된 SNAP 소매점 및 의료 시설.",
    "feature.ai": "EquityGuide AI",
    "feature.ai.desc": "혜택 자격, 80시간 근로 요건을 설명하고 근처 자원을 찾도록 도와주는 AI 어시스턴트.",
    "feature.screener": "자격 심사",
    "feature.screener.desc": "30초 이내에 SNAP 자격을 평가하는 단계별 가이드 — 계정 불필요.",
    "cta.title": "자원을 찾을 준비가 되셨나요?",
    "cta.subtitle": "주소로 검색하거나 지도를 탐색하거나 EquityGuide와 대화하세요.",
    "cta.button": "시작하기",
    "footer": "EquityMap · 오픈 데이터 · 워싱턴 D.C.",
    "search.placeholder": "주소 검색...",
    "chat.placeholder": "SNAP, Medicaid, 혜택에 대해 물어보세요...",
    "chat.welcome": "안녕하세요! 저는 EquityGuide입니다. D.C.의 식품, 의료 및 커뮤니티 자원을 안내하는 AI 어시스턴트입니다. 어떻게 도와드릴까요?",
    "chat.screener": "SNAP 자격 확인",
    "chat.work": "80시간 규칙이 뭔가요?",
    "chat.health": "건강 자원 찾기",
    "nearby": "근처 자원",
    "verified": "검증된 자원",
    "legend.food": "식품 / SNAP",
    "legend.health": "의료",
    "about.title": "EquityMap 소개",
    "about.body": "EquityMap은 D.C. 주민들이 2026년 연방 예산 변경으로 인한 '혜택 사막'을 탐색하도록 돕습니다.",
    "filters": "필터",
    "directions": "길찾기",
    "details": "상세",
    "close": "닫기",
    "get.directions": "길찾기",
  },
};

const LANG_NAMES: Record<LangCode, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  am: "አማርኛ",
  zh: "中文",
  ko: "한국어",
};

interface LangCtx {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: (key: string) => string;
  langName: string;
}

const LangContext = createContext<LangCtx>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
  langName: "English",
});

export const LangProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLangState] = useState<LangCode>(() => {
    if (typeof window === "undefined") return "en";
    return (localStorage.getItem("eq-lang") as LangCode) || "en";
  });

  const setLang = useCallback((l: LangCode) => {
    setLangState(l);
    localStorage.setItem("eq-lang", l);
  }, []);

  const t = useCallback(
    (key: string) => translations[lang]?.[key] || translations.en[key] || key,
    [lang]
  );

  return (
    <LangContext.Provider value={{ lang, setLang, t, langName: LANG_NAMES[lang] }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
